= Example Policies =
:author:
:date: 2017-04

The following examples show what to put into the `rules.conf` file in order to implement the given policy.

== Allow USB mass storage devices (USB flash disks) and block everything else ==

This policy will block any device that isn't just a mass storage device.
Devices with a hidden keyboard interface in a USB flash disk will be blocked.
Only devices with a single mass storage interface will be allowed to interact with the operating system.
The policy consists of a single rule:

 allow with-interface equals { 08:*:* }

The blocking is implicit in this case because we didn't write a `block` rule.
Implicit blocking is useful to desktop users because a desktop applet listening to USBGuard events can ask the user for a decision if an implicit target was selected for a device.

== Allow a specific Yubikey device to be connected via a specific port. Reject everything else on that port ==

 allow 1050:0011 name "Yubico Yubikey II" serial "0001234567" via-port "1-2" hash "044b5e168d40ee0245478416caf3d998"
 reject via-port "1-2"

We could use just the hash to match the device.
However, using the name and serial attributes allows the policy creator to quickly assign rules to specific devices without computing the hash.
On the other hand, the hash is the most specific value that identifies a device.
It's the best attribute to use if you want a rule to match just one specific device.

// TODO: explain that two physically separate devices can still have the same hash (e.g. keyboards)
WARNING: device hash warning text 

== Reject devices with suspicious combination of interfaces ==

A USB flash disk which implements a keyboard or a network interface is very suspicious.
The following set of rules forms a policy which allows USB flash disks and explicitly rejects devices with an additional and suspicious (as defined before) interface.

 allow with-interface equals { 08:*:* }
 reject with-interface all-of { 08:*:* 03:00:* }
 reject with-interface all-of { 08:*:* 03:01:* }
 reject with-interface all-of { 08:*:* e0:*:* }
 reject with-interface all-of { 08:*:* 02:*:* }

The policy rejects all USB flash disk devices with an interface from the HID/Keyboard, Communications and Wireless classes.
Please note that blacklisting is the wrong approach and you shouldn't just blacklist a set of devices and allow the rest.
The policy above assumes that blocking is the implicit default.
Rejecting a set of devices considered as "bad" is a good approach how to limit the exposure of the OS to such devices as much as possible.

== Allow a keyboard-only USB device only if there isn't already a USB device with a keyboard interface allowed ==

 allow with-interface one-of { 03:00:01 03:01:01 } if !allowed-matches(with-interface one-of { 03:00:01 03:01:01 })

== Play "Russian roulette" with USB devices ==

 allow if random(0.1666)
 reject

